### ISSUE TITLE
Programming languages with alphabet "M"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#10]
Many projects need to show a list of programming languages as checkboxes in their application. Hence the idea. I have finished till **K**. Can someone help me finish the alphabet **M** in `checkboxes.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by itsvipindev** [comment]
hello sir i can do it assign it to me

**Comment by itsvipindev** [comment]
Sir please review PR #47

**Comment by chilarai** [comment]
Thanks, @itsvipindev. It's amazing that you have completed all the issues assigned to you.
If you are interested in working on a Golang project, do send me an email mentioned on my GitHub Profile.
