### ISSUE TITLE
(Dropdown list) Basic CSS styles

### ISSUE THREAD

**Issue by guisantosfr** [chilarai/list-of-programming-languages#118]
The dropdowns in the list are not displayed properly, like in the image below.

![image](https://user-images.githubusercontent.com/32960040/193684575-ebdd76fb-8839-4eef-82a4-e5a24f46ee9c.png)

I recommend to do some basic CSS styles.

**Comment by guisantosfr** [comment]
@chilarai Could you assign this to me?

**Comment by chilarai** [comment]
Thanks sure @guisantosfr
