### ISSUE TITLE
Programming languages with alphabet "O"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#12]
Many projects need to show a list of programming languages as checkboxes in their application. Hence the idea. I have finished till **K**. Can someone help me finish the alphabet **O** in `checkboxes.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by ry-v1** [comment]
@chilarai - Can I work on this

**Comment by chilarai** [comment]
Alright @ry-v1
