### ISSUE TITLE
Thank you for your help in finishing the list

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#127]
@ShouryaSrivastava01 @Santhusha-bit @itsvipindev @guisantosfr @si-ddhant @Hanuvesh @viper-devil @AadityaNitin @Sscuber03 @shivam1317 @gabrielsozinho @Hamzawp @arthurmatthew @Shravanikale @giftade @yuvimalhotra28 @letdummy @ry-v1 @Tejas20-03 @Atulsoam562003 @roshan2152 @Neeraj-2307 @sanvisharma003 @HimangsKalita @yogitha02 @johnwatson484 @nikgautamgithub @Sonukumarkeshri4 @bindu-r02 @NyanCyanide @keshavgbpecdelhi @palash9561

**Comment by mahamat-abdelkerim-abakar** [comment]
could i contribute also

**Comment by chilarai** [comment]
> could i contribute also

If you look at the lists and find any missing languages, you are most welcome to add that. This goes for everyone
