### ISSUE TITLE
Programming languages with alphabet "Q"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#14]
Many projects need to show a list of programming languages as checkboxes in their application. Hence the idea. I have finished till **K**. Can someone help me finish the alphabet **Q** in `checkboxes.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by itsvipindev** [comment]
hello sir i can do it assign it to me

**Comment by itsvipindev** [comment]
sir please check PR #37
