### ISSUE TITLE
Programming languages with alphabet "V"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#19]
Many projects need to show a list of programming languages as checkboxes in their application. Hence the idea. I have finished till **K**. Can someone help me finish the alphabet **V** in `checkboxes.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by itsvipindev** [comment]
Hello sir i will do it assign it to me

**Comment by Sonukumarkeshri4** [comment]
Please assign it to me

**Comment by chilarai** [comment]
Hi @Sonukumarkeshri4 I am assigning this to you. I have already assigned another task to you @itsvipindev

**Comment by Sonukumarkeshri4** [comment]
please [check](https://github.com/chilarai/list-of-programming-languages/pull/43 )
