### ISSUE TITLE
Programming languages with alphabet "Y"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#22]
Many projects need to show a list of programming languages as checkboxes in their application. Hence the idea. I have finished till **K**. Can someone help me finish the alphabet **Y** in `checkboxes.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by Tejas20-03** [comment]
@chilarai Please Assign it to me

**Comment by chilarai** [comment]
Closed with PR #31

**Comment by Tejas20-03** [comment]
@chilarai Please Close this issue
