### ISSUE TITLE
Programming languages with alphabet "Z"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#23]
Many projects need to show a list of programming languages as checkboxes in their application. Hence the idea. I have finished till **K**. Can someone help me finish the alphabet **Z** in `checkboxes.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by itsvipindev** [comment]
i think i can help you in that can i work on it,
and also is there any way to filter out which programming languages i should add and which i shouldn;t thank you

**Comment by chilarai** [comment]
Hi @itsvipindev, thanks.
Lets add all the programming languages with "Z" in the list. Later, when a user wants to filter out, he can do it according to his application's needs

**Comment by chilarai** [comment]
Closed with PR #35
