### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "D"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#56]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **D** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by roshan2152** [comment]
Can you assign this to me?

**Comment by Shravanikale** [comment]
I want to work on this issue @chilarai  can you please assign this to me!!😊

**Comment by Atharv-Nalwade** [comment]
Oh actually I have worked on languages which start with D can I get assigned to it

**Comment by chilarai** [comment]
Sorry @Atharv-Nalwade, @Shravanikale, as @roshan2152 has asked for it first, I will have to assign this task to him. Just to be fair as there were no other criteria defined to assign in case of multiple requests.

I will update this in the `contributors.md` file as well

**Comment by Atharv-Nalwade** [comment]
Ok No problem

**Comment by chilarai** [comment]
Closed with PR #113
