### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "I"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#61]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **I** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by AadityaNitin** [comment]
Hey @chilarai I would like to take this issue could you please assign it to me?

**Comment by chilarai** [comment]
Sure
