### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "J"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#62]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **J** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by sanvisharma003** [comment]
heyy.. i would love to contribute.. what is it you are really looking to?

**Comment by chilarai** [comment]
I want to create a dropdown list in HTML starting alphabet `J`. If you look into this file
https://github.com/chilarai/list-of-programming-languages/blob/main/A-Z-dropdown.html, you will find a section for `J`. If you can help me fill that up, that will be awesome.

I have just begun adding `A` as an example.

This will help many people to easily add the list to their project

**Comment by sanvisharma003** [comment]
added for J and created a pull request.
taking part in hacktoberfest for the first time..so if there are any
changes needed , do ping me.

**Comment by chilarai** [comment]
Thanks @sanvisharma003. I have merged the PR #96
