### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "K"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#63]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **K** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by si-ddhant** [comment]
Hi I can work on this!

**Comment by chilarai** [comment]
Sure @si-ddhant

**Comment by chilarai** [comment]
Closed with PR #116
