### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "L"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#64]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **L** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by guisantosfr** [comment]
I'd like to work on this, please!

**Comment by chilarai** [comment]
Sure @guisantosfr

**Comment by chilarai** [comment]
Closed pr #115
