### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "O"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#67]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **O** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by giftade** [comment]
I'd like to solve this

**Comment by chilarai** [comment]
Sure
