### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "Q"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#69]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **Q** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by AadityaNitin** [comment]
Could you please assign me this isssue?

**Comment by Shravanikale** [comment]
@chilarai want to work on this issue  Please assign it to me !!😇

**Comment by chilarai** [comment]
Closed with PR #112
