### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "R"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#70]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **R** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by HimangsKalita** [comment]
would love to work on this

**Comment by HimangsKalita** [comment]
could you please check Added R programming languages #92

**Comment by chilarai** [comment]
Thank you @HimangsKalita
