### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "S"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#71]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **S** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by Sscuber03** [comment]
Hello @chilarai , Can this one also be assigned to me? I would love to contribute, and start my journey of contributing!

**Comment by chilarai** [comment]
Sure
