### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "T"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#72]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **T** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thankyou.

**Comment by chilarai** [comment]
Sure @Atulsoam562003

**Comment by chilarai** [comment]
Closed with PR #111
