### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "U"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#73]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **U** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by napalion** [comment]
Hii @chilarai, could you assign me for this issue? i would love to help

**Comment by chilarai** [comment]
Sure

**Comment by Hanuvesh** [comment]
hi , i want to work on this

**Comment by chilarai** [comment]
Sure @Hanuvesh

**Comment by Hanuvesh** [comment]
will this counted in hacktoberfest

**Comment by Hanuvesh** [comment]
can you assign me in 2 more task , i want to work on them , please assign me

**Comment by chilarai** [comment]
Sure. Feel free to take up any pending tasks
