### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "V"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#74]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **V** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by amitmishra11** [comment]
@chilarai please assign this issue to me

**Comment by arthurmatthew** [comment]
Hey, I'm going to work on this

**Comment by chilarai** [comment]
Sure @arthurmatthew

**Comment by chilarai** [comment]
Closed with PR #89
