### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "W"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#75]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **W** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by Neeraj-2307** [comment]
Hey, would love to contribute to this.

**Comment by chilarai** [comment]
Sure @Neeraj-2307

**Comment by chilarai** [comment]
Closed with PR #104
