### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "X"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#76]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **X** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by giftade** [comment]
I'll like to work on this issue

**Comment by chilarai** [comment]
Sure

**Comment by giftade** [comment]
Thanks
