### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "Y"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#77]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **Y** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by yogitha02** [comment]
@chilarai Please do assign me, i would be glad to finish the task

**Comment by chilarai** [comment]
Sure @yogitha02

**Comment by Hanuvesh** [comment]
please assign this task to me , it is not finish yet

**Comment by Hanuvesh** [comment]
It is showing this repo is not participating in hacktoberfest

**Comment by chilarai** [comment]
Where? Can you share screenshot and links

**Comment by ShouryaSrivastava01** [comment]
@chilarai Currently for repository is under Hacktoberfest. I've seen many repository getting excluded from hacktoberfest. Being a good maintainer is mandatory and I feel you are doing that job perfectly. Keep Hustling 👍

**Comment by chilarai** [comment]
Closed PR #124

**Comment by chilarai** [comment]
> @chilarai Currently for repository is under Hacktoberfest. I've seen many repository getting excluded from hacktoberfest. Being a good maintainer is mandatory and I feel you are doing that job perfectly. Keep Hustling 👍

Thanks @ShouryaSrivastava01. Yes, it takes time to verify and check each and every commit
