### ISSUE TITLE
(Dropdown list) Programming languages with alphabet "Z"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#78]
Many projects need to show a list of programming languages as a dropdown list in their application. Hence the idea. Can someone help me finish the alphabet **Z** in `A-Z-dropdown.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by Sscuber03** [comment]
Hello @chilarai !! Can this issue be assigned to me? I want to contribute in this repo!

**Comment by Sscuber03** [comment]
Thank you for accepting!

**Comment by Hanuvesh** [comment]
dropdown of z is not yet complete i want to work on it

**Comment by chilarai** [comment]
Closed with #124
