### ISSUE TITLE
'S' Section Dropdown is missing select field

### ISSUE THREAD

**Issue by arthurmatthew** [chilarai/list-of-programming-languages#88]
'S' Section Dropdown is missing select field making it appear as plain text and not a dropdown.

**Comment by arthurmatthew** [comment]
I am able to work on this issue. If you could assign me that would be great. Also, possibly label this issue with hacktoberfest.

**Comment by chilarai** [comment]
@arthurmatthew yes you are right. The `</select>` tag has been moved to the bottom of the file. We need to fix that.
Happy to assign that to you and yes, it will be labelled

**Comment by arthurmatthew** [comment]
Hi, thanks for assigning me. I have submitted a PR.

**Comment by chilarai** [comment]
Closed with PR #114
