### ISSUE TITLE
Programming languages with alphabet "L"

### ISSUE THREAD

**Issue by chilarai** [chilarai/list-of-programming-languages#9]
Many projects need to show a list of programming languages as checkboxes in their application. Hence the idea. I have finished till **K**. Can someone help me finish the alphabet **L** in `checkboxes.html`?

Here is the list from which I have referred to the list of programming languages
https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by Tejas20-03** [comment]
It will be my pleasure to contribute to this issue.

**Comment by chilarai** [comment]
Thanks @Tejas20-03. I have assigned

**Comment by Tejas20-03** [comment]
@chilarai Brother I have already done this, so can u pls close this issue..

**Comment by chilarai** [comment]
Thanks. Closed with PR #28
